<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Donation Receipt #{{ $donation->id }}</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; color: #1a1a2e; margin: 30px; font-size: 13px; }
        .header { text-align: center; border-bottom: 3px solid #E8541A; padding-bottom: 14px; }
        .header h1 { margin: 0; font-size: 20px; }
        .header p { margin: 3px 0 0; color: #666; font-size: 11px; }
        .receipt-no { margin-top: 18px; text-align: right; color: #666; font-size: 11px; }
        table.details { width: 100%; border-collapse: collapse; margin-top: 12px; }
        table.details td { padding: 9px 12px; border-bottom: 1px solid #eee; }
        table.details td:first-child { color: #666; width: 35%; }
        .amount { margin-top: 22px; background: #FFF4EF; border: 1px solid #E8541A; padding: 14px 18px; text-align: center; }
        .amount .value { font-size: 22px; font-weight: bold; color: #E8541A; }
        .footer { margin-top: 34px; text-align: center; color: #888; font-size: 10px; }
        .thanks { margin-top: 24px; text-align: center; font-style: italic; color: #444; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $parish_name }}</h1>
        <p>{{ $diocese }}</p>
        <p>{{ $address }}</p>
    </div>

    <p class="receipt-no">Receipt No. DON-{{ str_pad((string) $donation->id, 5, '0', STR_PAD_LEFT) }}<br>{{ $donation->donation_date->format('jS F, Y') }}</p>

    <table class="details">
        <tr>
            <td>Received from</td>
            <td><strong>{{ $donation->is_anonymous ? 'Anonymous donor' : ($donation->member?->full_name ?? $donation->donor_name ?? '—') }}</strong></td>
        </tr>
        <tr>
            <td>Purpose</td>
            <td>{{ $donation->purpose }}</td>
        </tr>
        <tr>
            <td>Payment method</td>
            <td>{{ ucwords(str_replace('_', ' ', $donation->payment_method)) }}@if($donation->transfer_reference) — ref. {{ $donation->transfer_reference }}@endif</td>
        </tr>
        @if($donation->notes)
        <tr>
            <td>Notes</td>
            <td>{{ $donation->notes }}</td>
        </tr>
        @endif
    </table>

    <div class="amount">
        <div>Amount received</div>
        <div class="value">&#8358;{{ number_format((float) $donation->amount, 2) }}</div>
    </div>

    <p class="thanks">"Each of you should give what you have decided in your heart to give." — 2 Corinthians 9:7<br>Thank you and God bless you.</p>

    <p class="footer">Generated by ParishHub on {{ now()->format('j M Y, g:i a') }}. This receipt is issued for parish records.</p>
</body>
</html>
